<?php
$showdefault = $this->getShowDefault();
$ApiKey = trim($this->getApikey());
$ApiSecrete = trim($this->getApiSecret());
$loginRadiusTitle = trim($this->getLoginRadiusTitle());
$UserAuth = $this->getApiResult($ApiKey, $ApiSecrete);
if ($showdefault == 1) {
    if ($this->user_is_already_login()) {
        echo '<div class="block"><div class="block-title"><strong><span>' . __('Social Login') . '</span></strong></div><div class="block-content"><p class="empty">';

        $userName = Mage::getSingleton('customer/session')->getCustomer()->getName();
        if ($loginRadiusAvatar = trim($this->getAvatar(Mage::getSingleton('customer/session')->getCustomer()->getId()))
        ) {
            echo "<img style='float:left' width='50' height='50' src='" . $loginRadiusAvatar . "' />";
        }
        echo "<span style='clear:both; float:left'>" . __("Welcome") . "!  $userName </span>";
        echo '</p></div></div>';

    } else {
        $this->getSocialLoginContainer();
    }

}
?>